<?php
/**
 * @file
 * Code for the Express Localist Bundle feature.
 */

include_once 'express_localist_bundle.features.inc';


function express_localist_bundle_tags_options() {
  $options = array();

  return $options;
}

function express_localist_bundle_places_options() {
  $options = array();

  return $options;
}

function express_localist_bundle_type_options() {
  $options = array();

  return $options;
}

function express_localist_bundle_content_match_options() {
  $options = array(
    'default' => 'At least one place, group, keyword or tag, and one filter item',
    'any' => 'Any place, group, keyword, tag, or filter item',
    'all' => 'At least one place and group, and all keywords, tags, and filter items',
    'or' => 'Any place or group, and at least one keyword or tag, and one filter item',
  );

  return $options;
}

function express_localist_bundle_widget_options() {
  $options = array();

  return $options;
}

function express_localist_bundle_style_options() {
  $options = array();

  return $options;
}
