<?php
/**
 * @file
 * Code for the Express Localist Bundle feature.
 */

include_once 'express_localist_bundle.features.inc';

function express_localist_bundle_menu() {
  $items = array();
  $items['admin/config/system/express-localist'] = array(
    'title' => 'Express Localist Configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('express_localist_bundle_config_form'),
    'access callback' => TRUE,
    'file' => 'express_localist_bundle.admin.inc',
  );
  return $items;
}

function express_localist_bundle_theme_registry_alter(&$theme_registry) {
  $module_path = drupal_get_path('module', 'express_localist_bundle');
  $theme_registry_copy = $theme_registry;
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'bean', $module_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('bean');
  foreach ($hooks as $h) {
	  if (isset($theme_registry[$h]['theme paths'])) {
	    $first_element = array_shift($theme_registry[$h]['theme paths']);
	    array_unshift($theme_registry[$h]['theme paths'], array_shift($theme_registry[$h]['theme paths']), $module_path);
  	}
  }
}


function express_localist_bundle_tags_options() {
  $options = array();
  $end_point = variable_get('express_localist_url', NULL);
  if (!$end_point) {
    return array();
  }
  else {
    $end_point .= '/api/2/tags';
  }

  $response = drupal_http_request($end_point);
  if ($response->code == '200') {
    $options = array();
    $terms = drupal_json_decode($response->data, true);
    dpm($terms);
    foreach ($terms['tags'] as $term) {
      $value = $term['tags']['urlname'];
      $display = $term['tags']['display_name'];
      $options[$value] = $display;
    }
  }

  return $options;
}

function express_localist_bundle_places_options() {
  $options = array();
  $end_point = variable_get('express_localist_url', NULL);
  if (!$end_point) {
    return array();
  }
  else {
    $end_point .= '/api/2/places';
  }

  $response = drupal_http_request($end_point);
  if ($response->code == '200') {
    $options = array();
    $terms = drupal_json_decode($response->data, true);
    foreach ($terms['places'] as $term) {
      $value = $term['place']['urlname'];
      $display = $term['place']['display_name'];
      $options[$value] = $display;
    }
  }

  return $options;
}

function express_localist_bundle_type_options() {
  $options = array();
  $end_point = variable_get('express_localist_url', NULL);
  if (!$end_point) {
    return array();
  }
  else {
    $end_point .= '/api/2/events/filters';
  }

  $response = drupal_http_request($end_point);
  if ($response->code == '200') {
    $options = array();
    $categories = array();
    $terms = drupal_json_decode($response->data, true);
    foreach ($terms['event_types'] as $term) {
      $value = $term['id'];
      $display = $term['name'];
      $options[$value] = $display;
    }
  }

  return $options;
}

function express_localist_bundle_content_match_options() {
  $options = array(
    'default' => 'At least one place, group, keyword or tag, and one filter item',
    'any' => 'Any place, group, keyword, tag, or filter item',
    'all' => 'At least one place and group, and all keywords, tags, and filter items',
    'or' => 'Any place or group, and at least one keyword or tag, and one filter item',
  );

  return $options;
}

function express_localist_bundle_widget_options() {
  $options = array(
    'view' => 'List',
    'combo' => 'Mini Grid + List',
  );

  return $options;
}

function express_localist_bundle_style_options() {
  $options = array(
    'modern' => 'Modern',
    'card' => 'Card',
    'classic' => 'Classic',
    'express-template-1' => 'Template 1',
    'express-template-2' => 'Template 2',
    'express-template-3' => 'Template 3',
    'express-template-4' => 'Template 4',
  );

  return $options;
}

function express_localist_bundle_category_options() {
  $options = array();
  $end_point = variable_get('express_localist_url', NULL);
  if (!$end_point) {
    return array();
  }
  else {
    $end_point .= '/api/2/events/filters';
  }

  $response = drupal_http_request($end_point);
  if ($response->code == '200') {
    $options = array();
    $categories = array();
    $terms = drupal_json_decode($response->data, true);

    // Sort everything alphabetically
    usort($terms['event_category'], function($a, $b) {
      return strcmp($a['name'], $b['name']);
    });

    // Build tree
    $tree = _express_localist_bundle_tree($terms['event_category']);

    $test = _express_localist_bundle_tree_options($tree);
    $options = _express_localist_bundle_tree_options($tree);
  }

  return $options;
}

function _express_localist_bundle_tree(array $elements, $parentId = NULL) {
  $branch = array();

  foreach ($elements as $element) {
    if ($element['parent_id'] == $parentId) {
      $children = _express_localist_bundle_tree($elements, $element['id']);
      if ($children) {
        $element['children'] = $children;
      }
      $branch[] = $element;
    }
  }
  return $branch;
}

function _express_localist_bundle_tree_options($tree, $depth = 0) {
  if (!is_array($tree)) {
    return false;
  }
  $result = array();
  foreach ($tree as $key => $value) {
    $id = $value['id'];
    $indent = '';
    for ($i = 0; $i < $depth; $i++) {
      $indent .= '-';
    }
    $name = $indent . ' ' . $value['name'];
    $result[$id] = $name;
    if (!empty($value['children'])) {
      $indent = $depth +1;
      $children = _express_localist_bundle_tree_options($value['children'], $indent);
      $result = $result + $children;
    }

  }
  return $result;
}

function express_localist_bundle_preprocess_entity(&$vars) {
  $entity_type = $vars['elements']['#entity_type'];
  $bundle = $vars['elements']['#bundle'];

  // Only preprocess block row beans.
  if ($entity_type == 'bean' && $bundle == 'localist_events') {
    $end_point = variable_get('express_localist_url', NULL);
    $end_point = str_replace('http://', '//', $end_point);
    $values = array();
    $values['schools'] = 'ucboulder';
    $values['num'] = $vars['field_localist_results'][0]['value'];
    $values['days'] = $vars['field_localist_days_ahead'][0]['value'];

    $values['picks'] = $vars['field_localist_show_featured'][0]['value'];
    $values['sponsored'] = $vars['field_localist_show_sponsored'][0]['value'];
    $values['include_matching'] = $vars['field_localist_include_matching'][0]['value'];
    $values['content_match'] = $vars['field_localist_content_match'][0]['value'];
    $values['hide_past'] = $vars['field_localist_hide_past_events'][0]['value'];
    $values['hidedesc'] = $vars['field_localist_hide_descriptions'][0]['value'];
    $values['expand_descriptions'] = $vars['field_localist_truncate_desc'][0]['value'];
    $values['html_descriptions'] = $vars['field_localist_render_html'][0]['value'];
    $values['hideimage'] = $vars['field_localist_hide_images'][0]['value'];
    $values['show_times'] = $vars['field_localist_hide_times'][0]['value'];
    $values['target_blank'] = $vars['field_localist_new_window'][0]['value'];
    $values['skip_recurring'] = $vars['field_localist_skip_recurring'][0]['value'];
    $values['all_instances'] = $vars['field_localist_all_instances'][0]['value'];

    $values['template'] = $vars['field_localist_style'][0]['value'];

    $configs = array();
    foreach ($values as $key => $value) {
      // Special rules for configs come first.
      //
      // Show Times is a backwards value.
      // Widget option is 'Hide Times' - added only if = 0.
      if ($key == 'show_times' && $value == 1) {
        $configs[] = $key . '=0';
      }
      // If classic template is chosen, value should not be added.
      elseif ($key == 'template' && $value == 'classic') {
        //$configs[] = $key . '=' . $value;
      }
      elseif (is_numeric($value) && $value != 0) {
        $configs[] = $key . '=' . $value;
      }
      elseif (!is_numeric($value)) {
        $configs[] = $key . '=' . $value;
      }
    }

    $type = $vars['field_localist_widget_type'][0]['value'];
    $vars['widget_url'] = $end_point . '/widget/' . $type . '?' . join('&', $configs);
    $vars['widget_configs'] = $configs;

  }
}

/**
 * Implements hook_form_FORMID_alter.
 *
 * Add States to localist_events form.
 */
function express_localist_bundle_form_bean_form_alter(&$form, &$form_state, $form_id) {
  if ($form['bean']['#value']->type == 'localist_events') {
    // Delete start date default value if this is a new bean.
    if ($form['bean']['#value']->bid == NULL) {
      unset($form['field_localist_start_date'][LANGUAGE_NONE][0]['#default_value']['value']);
      unset($form['field_localist_start_date'][LANGUAGE_NONE][0]['#default_value']['value2']);
    }
  }
}
/**
 * Implements hook_inline_entity_form_entity_form_alter.
 *
 * Add States to localist_events form when used in inline entity form.
 */
function express_localist_bundle_inline_entity_form_entity_form_alter(&$entity_form, &$form_state) {

  if ($entity_form['#entity']->type == 'localist_events') {
    // Delete start date default value if this is a new bean.
    if ($entity_form['#entity']->bid == NULL) {
      unset($entity_form['field_localist_start_date'][LANGUAGE_NONE][0]['#default_value']['value']);
      unset($entity_form['field_localist_start_date'][LANGUAGE_NONE][0]['#default_value']['value2']);
    }
  }
}

/**
 * Implements hook_secure_permissions().
 *
 */
function express_localist_bundle_secure_permissions($role) {
  $permissions = array(
    'anonymous user' => array(
      'view any localist_events bean',
    ),
    'authenticated user' => array(
      'view any localist_events bean',
    ),
    'administrator' => array(
      'create any localist_events bean',
      'delete any localist_events bean',
      'edit any localist_events bean',
      'view any localist_events bean',
    ),
    'content_editor' => array(
      'create any localist_events bean',
      'delete any localist_events bean',
      'edit any localist_events bean',
      'view any localist_events bean',
    ),
    'developer' => array(
      'create any localist_events bean',
      'delete any localist_events bean',
      'edit any localist_events bean',
      'view any localist_events bean',
      'administer block wrapper',
    ),
    'site_owner' => array(
      'create any localist_events bean',
      'delete any localist_events bean',
      'edit any localist_events bean',
      'view any localist_events bean',
    ),
  );

  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}
